services:
  catalogdb:
   image: mongo
 
  basketdb:
   image: redis:alpine

  discountdb:
   image: postgres:17

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  catalog:
   image: ${DOCKER_REGISTRY-}catalog
   build:
     context: .
     dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount:
    image: ${DOCKER_REGISTRY-}discount
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  ordering:
    image: ${DOCKER_REGISTRY-}ordering
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  
volumes:
 mongo_data:
 postgres_data:
 orderdb-data: